### PR TITLE
Fix very old bug in Watcom code

### PR DESCRIPTION
**Pull request by jmalak**

### CODE REVIEW

**Comment by gvanem** [comment]
Thanks for the PR. But please explain when `__386__`  is defined (and `__FLAT__` is not)?
`__FLAT__`  is also defined for ` wcc386 -mf`.

**Comment by jmalak** [comment]
It is simple __FLAT__ is memory model not architecture
__386__ is compiler macro for 32-bit architecture
__I86__ is compiler macro for 16-bit architecture (alternative macros are M_I86, _M_I86)
By example if I use __SMALL__ memory model it can be for 16-bit architecture or for 32-bit architecture. I understand that __FLAT__ is used for 32-bit but it is not same as 32-bit architecture.

**Comment by jmalak** [comment]
Anyway 
`wcc386 -ms` define `__386__` and `__SMALL__` macros
`wcc -ms` define `__I86__` and `__SMALL__` macros
`wcc386 -mf` define `__386__` and `__FLAT__` macros
`wcc -mf` is not allowed

**Comment by gvanem** [comment]
Merged. Thanks!

**Comment by jmalak** [comment]
There is mistake proper macro is '__I86__'.
Macro '__86__' is not defined by Watcom compiler, that break 16-bit code.
Below are Watcom macros defined by architecture
```
      16-bit      32-bit
     ========    ========

     __X86__     __X86__
     __I86__     __386__
     M_I86       M_I386
     _M_I86      _M_I386
     _M_IX86     _M_IX86
```

**Pull request merged**
