### PR TITLE
add 32-bit small memory model for WATCOM

### PR DESCRIPTION
**Pull request by jmalak**

### CODE REVIEW

**Comment by gvanem** [comment]
Have you actually tested `SMALL32` with e.g. `bin/ping.c`? Does it work?

**Comment by gvanem** [comment]
Merged.

**Comment by jmalak** [comment]
I am still working on fixing compilation errors etc.
How I can build/run tests?

**Comment by gvanem** [comment]
You can try `cd src\tests & configur.bat watcom & make -f watcom_f.mak` etc. But Watcom is not fully supported in many test programs.

**NB**, needs GNU-make.

**Comment by jmalak** [comment]
Next question.
tests has some preffered or restricted host platforms to run or I can run on any platform or on combination of platforms?

**Comment by gvanem** [comment]
Since I no longer have a DOS platform, I'm not sure. Try it.
Last time I really tested DOS, Pharlap, djgpp etc. was back in 2002 when I had Win-XP. I still have that PC, but is probably no good. 

But I tried `vDosPlus` with a Watcom/small version of `tcpinfo.exe`. It worked, but since it has no PacketDrvr, it's little use. Maybe DOSbox or VirtualBox is possible?

**Comment by jmalak** [comment]
I have one Virtual Machine with Windows XP that I could use it for test or I could use DosBox on my Windows 10. I think that packet driver for VM emulated network adapter could be available.

**Pull request merged**
