### PR TITLE
 correct EOL of source file

### PR DESCRIPTION
**Pull request by jmalak**

### CODE REVIEW

**Comment by gvanem** [comment]
You have changed this into Unix EOL format (LF only)?

What happens with this file in a .zip downloaded from Github and used in e.g. Notepad?

**Comment by jmalak** [comment]
No, it correct EOL saved in repository (it is LF) but EOL for files is determined by git user setup.
I have a problem that in repository this file (only this one) was saved with crlf that if cloned to Linux it has crlf too, but all others were correct with lf only. On Windows you have all files with crlf. 
Now this file is with lf on Linux and with crlf on Windows.
What will be in ZIP file is determined by how Github get files from repository probably it will be as is in repository that it will be lf only. Anyway mkmake on Linux is not working with crlf that is necesary to have makefile.all and others with lf.

But it is general problem if you want to use any git export on Windows that you must correct EOL or use editor which works on Windows with lf.
Best is to use git client and you get EOL current for client platform.

**Comment by gvanem** [comment]
> Best is to use git client and you get EOL current for client platform.

But can we assume the average user have Git installed? Many user D/L from
Github with the *Download ZIP* feature. All the files therein have LF ending. 

It's also best to fix `mkmake.c` to work on Unix with CRLF endings.

**Comment by gvanem** [comment]
But anyway, since all/most (?) text-files here are LF, I'm merging.

**Comment by jmalak** [comment]
I think that other mk* utility will have this problem. I don't know it could be also problem with GNU tools. Most of OW tools has no problem with this because they are designed as multi-OS/platform and handle various EOL.

**Comment by jmalak** [comment]
There are *.bat files with crlf in repository also, but it is correct because they are used only on DOS-ish platforms where it is required.

**Comment by jmalak** [comment]
Anyway I think that output file from mkmake will have host EOL even if entry file will have lf only EOL.

**Comment by jmalak** [comment]
I check it and I can confirm on Windows if I changed makefile.all to have lf EOL then output make file has crlf EOL.

**Comment by gvanem** [comment]
I wrote this little Python [script](https://github.com/gvanem/Watt-32/blob/master/util/check_EOL.py) that check for these things. 

*PS*. Not yet Python 3.x compatible.

**Comment by jmalak** [comment]
Now all files have correct EOL in git repository EOL is lf except *.bat files which have crlf EOL (they will be loaded from repository always with crlf. All others will be with platform EOL and ZIP file is with lf EOL.

**Pull request merged**
