### PR TITLE
fix type mismatch

### PR DESCRIPTION
**Pull request by jmalak**

### CODE REVIEW

**Comment by gvanem** [comment]
What's this all about? The `_dx_*()`  functions are for Pharlap.

**Comment by jmalak** [comment]
some of _dx_... functions are also used for Flashtek (X32VM) in watt32. OW supports both extenders and I am compiling for both localy (I have appropriate SDK).

**Comment by gvanem** [comment]
I know. I wrote those `_dx_*()` functions for X32VM. 
But my point was; what is you PR trying to solve?

**Comment by jmalak** [comment]
Oh sorry, I did mistake if I copied code change. Correct code fragment is.

```
#if (DOSX & (PHARLAP|X32VM))
    _dx_call_real (old_int_8, &rmBlock_int8, 1);
#elif defined(__WATCOMC__)
    _chain_intr (old_int_8);    /* chain now */
#else
    (*old_int_8)();
#endif
```

**Comment by gvanem** [comment]
For the 3rd time, what is this change good for? Simply swapping those `#if ()` statements.

The code is probably of no use anyway. So I could delete all this `init_timer_isr()` stuff. Unless you/someone prove it works in one of the `src/tests/` programs.

**Comment by jmalak** [comment]
The reason was to fix type mismatch for WATCOM
For Pharlap and Flashtek must be used theirs internal prototype even if it is compiled by WATCOM.
For other targets is used for WATCOM chain_intr with WATCOM prototype.
I didn't study much code if it is removable, only fix type mismatches for Watcom compiler.

**Comment by gvanem** [comment]
Okay, merging. Thanks.

**Comment by gvanem** [comment]
This change broke `wmake_f.mak`: https://ci.appveyor.com/project/gvanem/watt-32/build/job/14cdcs81s0c76jrk

I'm reverting.

**Pull request merged**
