### PR TITLE
replace OBJDIR macro by OBJPATH to remove dependency on path separator

### PR DESCRIPTION
**Pull request by jmalak**

### CODE REVIEW

**Comment by gvanem** [comment]
Why is the syntax `$(OBJPATH)misc.obj` better on Linux?

**Comment by jmalak** [comment]
there is not hardcoded path separator. This reference works the same way on all platforms DOS/Windows/Linux that you can use it for rules etc.

**Comment by gvanem** [comment]
Okay, merging.

**Comment by gvanem** [comment]
Closing and merging by hand. Thanks.

**Pull request closed without merging**
