### PR TITLE
Only reply to ACK if we have more data to send

### PR DESCRIPTION
**Pull request by jwt27**
fixes: #100

I re-ordered the logic a bit, hopefully this makes it easier to follow.

### CODE REVIEW

**Comment by jwt27** [comment]
BTW, maybe receiving a PUSH bit is a good reason to do fast-ACK.

**Comment by gvanem** [comment]
> BTW, maybe receiving a PUSH bit is a good reason to do fast-ACK.

Not sure what you mean here.

But most important; what does WireShark say now about *Dup ACKS* and how has the rate improved?

**Comment by jwt27** [comment]
Dup ACKs are gone now, and transfer rate is about 1900 KB/s.  This can be improved further if we set PUSH bit less often, I'm working on that now.

Linux seems to send a fast-ACK when it receives a segment with PUSH set.  Otherwise it does delayed-ACK, so then we have fewer ACKs to process.

For the comment about "needing a better criteria for doing Fast-ACK", I think we can also copy this behavior.

**Comment by gvanem** [comment]
Merged and many thanks again.

**Comment by jwt27** [comment]
Just noticed I introduced a sign-compare warning here, oops.

**Pull request merged**
