### PR TITLE
correct WATCOM compilers setup to separate architecture and memory mo…

### PR DESCRIPTION
**Pull request by jmalak**
…del in configuration

### CODE REVIEW

**Comment by gvanem** [comment]
Thanks for this PR too.

But in the future, please use a sensible small, subject and more details in the commit message.

**Comment by gvanem** [comment]
Merged.

**Comment by gvanem** [comment]
I forgot to ask; does OpenWatcom for Watt-32 only have these CPU identifiers to care about:
`__I86__` and `__386__`. 

I guess stuff like `__PPC__`, `__AXP__` etc are safe to ignore.

**Comment by jmalak** [comment]
Watcom doesn't support Apha and PPC officialy.
WATCOM compilers are capable to generate code for these processor, but it is completely untested and not complete.

**Comment by gvanem** [comment]
Ok. Good to know.

**Pull request merged**
